'use client';

import { useEffect, useState } from 'react';
import { StatTile } from '@/components/StatTile';
import { useToast } from '@/components/ToastProvider';
import type { ReportResult, SprintData } from '@/lib/types';

function firstSentences(text: string, count: number): string {
  const parts = text.split(/(?<=[.!?])\s+/).filter(Boolean);
  return parts.slice(0, count).join(' ');
}

export default function ReportPage() {
  const { showToast } = useToast();
  const [sprintData, setSprintData] = useState<SprintData | null>(null);
  const [sprintError, setSprintError] = useState<string | null>(null);
  const [report, setReport] = useState<ReportResult | null>(null);
  const [missingDocCount, setMissingDocCount] = useState(0);
  const [generating, setGenerating] = useState(false);
  const [sending, setSending] = useState(false);

  useEffect(() => {
    loadSprint();
  }, []);

  async function loadSprint() {
    setSprintError(null);
    try {
      const res = await fetch('/api/sprint');
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? 'Failed to load sprint data');
      setSprintData(data);
    } catch (err) {
      setSprintError(err instanceof Error ? err.message : 'Failed to load sprint data');
    }
  }

  async function generateReport() {
    setGenerating(true);
    try {
      const [reportRes, docLinksRes] = await Promise.all([
        fetch('/api/report', { method: 'POST' }),
        fetch('/api/doc-links'),
      ]);
      const reportData = await reportRes.json();
      if (!reportRes.ok) throw new Error(reportData.error ?? 'Failed to generate report');
      setReport(reportData);

      const docLinksData = await docLinksRes.json();
      setMissingDocCount(docLinksRes.ok ? docLinksData.missingDocTicketIds.length : 0);
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Failed to generate report', 'error');
    } finally {
      setGenerating(false);
    }
  }

  async function sendToTeams() {
    if (!report) return;
    setSending(true);
    try {
      const res = await fetch('/api/teams/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sprintId: report.sprintId,
          sprintName: report.sprintName,
          summary: firstSentences(report.narrative, 2),
          doneCount: sprintData?.tickets.filter((t) => t.status === 'done').length ?? 0,
          totalCount: sprintData?.tickets.length ?? 0,
          velocity: report.velocity,
          missingDocCount,
        }),
      });
      const data = await res.json();
      if (!res.ok || !data.ok) {
        showToast(`Could not send to Teams: ${data.error ?? 'unknown error'}`, 'error');
      } else {
        showToast('Report summary sent to Teams', 'success');
      }
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Could not send to Teams', 'error');
    } finally {
      setSending(false);
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Auto Report</h1>
          <p className="text-sm text-gray-500">
            {sprintData ? `${sprintData.sprint.name} · ${sprintData.sprint.startDate} → ${sprintData.sprint.endDate}` : 'Loading sprint…'}
          </p>
        </div>
        <button
          onClick={loadSprint}
          className="rounded border px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
        >
          Refresh data
        </button>
      </div>

      {sprintError && (
        <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{sprintError}</div>
      )}

      {sprintData && !report && (
        <button
          onClick={generateReport}
          disabled={generating}
          className="rounded bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700 disabled:opacity-50"
        >
          {generating ? 'Generating…' : 'Generate Report'}
        </button>
      )}

      {report && (
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <StatTile label="Velocity (points)" value={report.velocity} />
            <StatTile label="Completion rate" value={`${Math.round(report.completionRate * 100)}%`} />
            <StatTile label="Open bugs" value={report.openBugCount} />
            <StatTile label="Closed bugs" value={report.closedBugCount} />
          </div>

          <div className="rounded-lg border bg-white p-4">
            <p className="text-sm leading-relaxed text-gray-800">{report.narrative}</p>
            <p className="mt-2 text-xs text-gray-400">
              {report.generatedByLLM ? 'Generated by Gemini' : 'Generated by template (no API key set)'}
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={sendToTeams}
              disabled={sending}
              className="rounded bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700 disabled:opacity-50"
            >
              {sending ? 'Sending…' : 'Send to Teams'}
            </button>
            <button
              onClick={generateReport}
              disabled={generating}
              className="rounded border px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
            >
              Regenerate
            </button>
          </div>
        </div>
      )}

      {sprintData && (
        <div className="rounded-lg border bg-white">
          <table className="w-full text-left text-sm">
            <thead className="border-b bg-gray-50 text-xs uppercase text-gray-500">
              <tr>
                <th className="px-3 py-2">Ticket</th>
                <th className="px-3 py-2">Type</th>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2">Points</th>
                <th className="px-3 py-2">Assignee</th>
              </tr>
            </thead>
            <tbody>
              {sprintData.tickets.map((t) => (
                <tr key={t.id} className="border-b last:border-0">
                  <td className="px-3 py-2 font-medium text-gray-900">
                    {t.id} — {t.title}
                  </td>
                  <td className="px-3 py-2 capitalize text-gray-600">{t.type}</td>
                  <td className="px-3 py-2 capitalize text-gray-600">{t.status.replace('_', ' ')}</td>
                  <td className="px-3 py-2 text-gray-600">{t.storyPoints}</td>
                  <td className="px-3 py-2 text-gray-600">{t.assignee}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
